### ISSUE TITLE
About the generalization of Per-FedAvg in the code

### ISSUE THREAD

**Issue by skydvn** [KarhouTam/PerFedAvg#1]
Dear author, 
I have do this experiment on your code, and here is what i have got
![image](https://user-images.githubusercontent.com/62003737/209975139-3df407a1-848b-4b93-abb2-2df2eaa8f437.png)
as you can see from the image, I execute the get_data_batch from your code with a long loop.

Because of your code's number of batches are limited in 7 batches each user. The next(iter(set)) will be fix the batch after the 7th loop. May be it will make the code not learning well. To my extense of knowledge :)

**Comment by KarhouTam** [comment]
First, thanks for your interest in my reproduction.
Thanks for your correction. I would fix the code soon.
